# Generated by Django 3.1.2 on 2021-07-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapp', '0002_auto_20210722_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
